<?php

namespace SMMI\ConnexionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConnexionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnexionRepository extends EntityRepository
{
}
