smmi_back_office:
    resource: "@SMMIBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /gestion

smmi_index:
    resource: "@SMMIIndexBundle/Resources/config/routing.yml"
    prefix:   /

smmi_cours:
    resource: "@SMMICoursBundle/Resources/config/routing.yml"
    prefix:   /

smmi_quizz:
    resource: "@SMMIQuizzBundle/Resources/config/routing.yml"
    prefix:   /quizz

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
