smmi_cours_liste:
    path:     /module/cours
    defaults: { _controller: SMMICoursBundle:Cours:liste }

smmi_cours_module:
    path:     /module
    defaults: { _controller: SMMICoursBundle:Cours:module }

