smmi_backoffice_liste:
    path:     /
    defaults: { _controller: SMMIBackOfficeBundle:BackOffice:liste }

smmi_backoffice_add:
    path:     /ajouter-cours
    defaults: { _controller: SMMIBackOfficeBundle:BackOffice:add }